### ISSUE TITLE
CVE Reference list incorrectly parsed

### ISSUE THREAD

**Issue by elliseghan** [segps/segps-code#1]
Sometimes reference list includes references with incomplete information such as type, source or URL.
Currently, the implementation  (@isultane) cannot correctly deal with a list having missing components.

**Comment by elliseghan** [comment]
Using the current nvd xml feeds from [NVD Data Feed](https://nvd.nist.gov/download.cfm) and the previous version of the parsing code shown below, there is no longer any ArrayIndexOutOfBoundsException. We need further tests to confirm a fix.
```java
for (int index = 0; index < rfl.size();) {
        String ReferenceType = "", ReferenceSource = "", ReferenceURL = "";
	ReferenceType = rfl.get(index);
	ReferenceSource = rfl.get(index + 1);
	ReferenceURL = rfl.get(index + 2);
        //code to create triples
        index+=3;
}
```

**Comment by isultane** [comment]
I uploaded tested the code and uploaded the new triples on the server. Should we close this bug?
